spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mzansibuilds
    username: mzansiuser
    password: mzansipass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: mzansi_secret_key_change_this_in_prod
    expiration: 604800000